spring.application.name=notification-service

# Centralizovana konfiguracija (Task 4 - Config Server)
spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.fail-fast=true

# Default port ako Config Server nije dostupan
server.port=8086

# Aktivni profil (dev/test profili podrzani kroz config-server)
spring.profiles.active=dev
