version: '3.8'

services:
  # 1. MySQL Database
  mysql-db:
    image: mysql:8.0
    container_name: booking_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 1.5 RabbitMQ (Saga Pattern)
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # 2. Eureka Server (Service Discovery)
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"

  # 3. Config Server
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      eureka-server:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8888/application/default || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 4. API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - APP_JWT_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAugRSmCOipKNml+04CQrYH2JcUT24HcgabT37pHDZaBeC49pkrGVm2NfZkXZ7QJm3TW8uFNPnfBdrZyMgXLJZ9UoNsgXg7QLO7KvNCllDXTnh63Yt8SFc5ht7D6ACXba3WVTlIJHYeh1p2JVj6h0LUY1jxRiPMo4NqfTcfb3XWB8Bxwih5M+wzfywb3BWcaOOk6qA8Xh/Zh/V/BkTu2NWuGRRMqtrUDqDTPC0W72E5H14wElgFPz4Ipru+CtJnG6z2oOskguyg2gWpXTwRBQR1YaMaI+Knto6Wxrgq1HE9ibz9H8mDcT3oziQ0XLDzoAfZ8KzzQHnzZehM75RL6u7uwIDAQAB

  # 5. Frontend React App
  booking-app:
    build:
      context: ./booking-app
      dockerfile: Dockerfile
    container_name: booking-app
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    environment:
      - VITE_API_URL=http://localhost:8080

  # --- Business Microservices ---

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - APP_JWT_PRIVATE_KEY=MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC6BFKYI6Kko2aX7TgJCtgfYlxRPbgdyBptPfukcNloF4Lj2mSsZWbY19mRdntAmbdNby4U0+d8F2tnIyBcsln1Sg2yBeDtAs7sq80KWUNdOeHrdi3xIVzmG3sPoAJdtrdZVOUgkdh6HWnYlWPqHQtRjWPFGI8yjg2p9Nx9vddYHwHHCKHkz7DN/LBvcFZxo46TqoDxeH9mH9X8GRO7Y1a4ZFEyq2tQOoNM8LRbvYTkfXjASWAU/Pgimu74K0mcbrPag6ySC7KDaBaldPBEFBHVhoxoj4qe2jpbGuCrUcT2JvP0fyYNxPejOJDRcsPOgB9nwrPNAefNl6EzvlEvq7u7AgMBAAECggEAGQDFvU9k6C5Sdu9azdRYUnedIwphuhcQfkiLj4Hfpx8p58iOKaIDnff9dZDwZjGDMvRTxFbrUYGwXQ+apPsQHmlSx/AEWLc86xD4oYB4DoreNBERgczTONbOxr3iM4iAwpAnsCYKa/eSJ5uE743x3IddtrtjXA8+BO81x+0BigV+HzEVaHZj/B+YrFRml2NRKrZkwjMxiQaL1kfSWuWwZiJsRL2R/9Na8Jh5iX2mv2VKyUnRQ2657jxr5mDcNLfjRbw5pnPAOFgpqQcmy7kvvgxtv9rEM5nITyeJVy1rVHUBke/lbAqY9rByFLHAYmMxQqgb9fH6SY+cklNEJl4sAQKBgQDqL8FXvk444IeMWWOkKGsB0cNIiONPr9L3WVCnt7apCDLtzr8pTlSb3oP9Zf3g1oUl81xkqeG0mQh6DbonfFw7d/Qh6O1aEsDsNZ2MqNeRFGuuiyRFltOrf5PkyyJyGKbAN8l9l6k5pr+oZMjUTfrrSQw92LcpnWAHLt0mq89eAQKBgQDLV/K7tKZc+RCurlts7FCgHH/sVpDzfa/MRjQw/87f+B/htu0jIgeI3h+y3QMVvZXqvpwtDDFl3Bh7on5PYsPNSJ+oznNUdLXe30vmh9pg+823D1w23i2Pjox2Si2Qtgaja8K5o2oIZ1GB814Gg7NGm3YwQ5Kav0JhJe1FUfQRuwKBgQDPNEW7XtRTGsaT9Ztl6aUUTQaeLRACt6zP0aS9YJ0rXefB5YXaBEZ0SyM5l35T6zqP441CO9VKN4T6iR7GRRBORcoqHq+zXJh55s5pYBKreQf1vYLwV40dVpoCe4EUtp8Dv9h1WTUPn2xAkDvpLL3wZAeCyTb2iRooAN0HlEi8AQKBgCKbm1JbEp1sPmycfC7zoV0+vH7q1My8LXlk0WktgHYZ8sMlsQJzvjiLJXX5q5a9p5BGVKpOEvI1HW2dYEX+lziPDa1bRcGwA2wlMPPRV1d+Q6rOUHF+Kt7t8fYH9e1VLZgOtRuHNnqrqvGlC/Gr5I011E2uknsH5jJGlDViF1oVAoGAaPrtkUUvUDk0LYK3Yfipa+6kN/0puq2K/JBTCtwYQlbvlGz995KhDQ1YnVCHMJjgFPAm3gsguyum82UH3TP4VWocGRUC2euLxZZWioRTOBQkuCD6XTY+HapSQci3GiDZqlhlB3ApQy3ffvvQ/h/kJV97nzdYIlhv+AguM5SXldQ=
      - APP_JWT_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAugRSmCOipKNml+04CQrYH2JcUT24HcgabT37pHDZaBeC49pkrGVm2NfZkXZ7QJm3TW8uFNPnfBdrZyMgXLJZ9UoNsgXg7QLO7KvNCllDXTnh63Yt8SFc5ht7D6ACXba3WVTlIJHYeh1p2JVj6h0LUY1jxRiPMo4NqfTcfb3XWB8Bxwih5M+wzfywb3BWcaOOk6qA8Xh/Zh/V/BkTu2NWuGRRMqtrUDqDTPC0W72E5H14wElgFPz4Ipru+CtJnG6z2oOskguyg2gWpXTwRBQR1YaMaI+Knto6Wxrgq1HE9ibz9H8mDcT3oziQ0XLDzoAfZ8KzzQHnzZehM75RL6u7uwIDAQAB
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy

  property-service-1:
    build:
      context: ./property-service
      dockerfile: Dockerfile
    container_name: property-service-1
    environment:
      - SERVER_PORT=8082
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - APP_JWT_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAugRSmCOipKNml+04CQrYH2JcUT24HcgabT37pHDZaBeC49pkrGVm2NfZkXZ7QJm3TW8uFNPnfBdrZyMgXLJZ9UoNsgXg7QLO7KvNCllDXTnh63Yt8SFc5ht7D6ACXba3WVTlIJHYeh1p2JVj6h0LUY1jxRiPMo4NqfTcfb3XWB8Bxwih5M+wzfywb3BWcaOOk6qA8Xh/Zh/V/BkTu2NWuGRRMqtrUDqDTPC0W72E5H14wElgFPz4Ipru+CtJnG6z2oOskguyg2gWpXTwRBQR1YaMaI+Knto6Wxrgq1HE9ibz9H8mDcT3oziQ0XLDzoAfZ8KzzQHnzZehM75RL6u7uwIDAQAB
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      config-server:
        condition: service_healthy

  property-service-2:
    build:
      context: ./property-service
      dockerfile: Dockerfile
    container_name: property-service-2
    environment:
      - SERVER_PORT=8085
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - APP_JWT_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAugRSmCOipKNml+04CQrYH2JcUT24HcgabT37pHDZaBeC49pkrGVm2NfZkXZ7QJm3TW8uFNPnfBdrZyMgXLJZ9UoNsgXg7QLO7KvNCllDXTnh63Yt8SFc5ht7D6ACXba3WVTlIJHYeh1p2JVj6h0LUY1jxRiPMo4NqfTcfb3XWB8Bxwih5M+wzfywb3BWcaOOk6qA8Xh/Zh/V/BkTu2NWuGRRMqtrUDqDTPC0W72E5H14wElgFPz4Ipru+CtJnG6z2oOskguyg2gWpXTwRBQR1YaMaI+Knto6Wxrgq1HE9ibz9H8mDcT3oziQ0XLDzoAfZ8KzzQHnzZehM75RL6u7uwIDAQAB
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      config-server:
        condition: service_healthy

  reservation-service:
    build:
      context: ./reservation-service
      dockerfile: Dockerfile
    container_name: reservation-service
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - APP_JWT_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAugRSmCOipKNml+04CQrYH2JcUT24HcgabT37pHDZaBeC49pkrGVm2NfZkXZ7QJm3TW8uFNPnfBdrZyMgXLJZ9UoNsgXg7QLO7KvNCllDXTnh63Yt8SFc5ht7D6ACXba3WVTlIJHYeh1p2JVj6h0LUY1jxRiPMo4NqfTcfb3XWB8Bxwih5M+wzfywb3BWcaOOk6qA8Xh/Zh/V/BkTu2NWuGRRMqtrUDqDTPC0W72E5H14wElgFPz4Ipru+CtJnG6z2oOskguyg2gWpXTwRBQR1YaMaI+Knto6Wxrgq1HE9ibz9H8mDcT3oziQ0XLDzoAfZ8KzzQHnzZehM75RL6u7uwIDAQAB
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8084:8084"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - APP_JWT_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAugRSmCOipKNml+04CQrYH2JcUT24HcgabT37pHDZaBeC49pkrGVm2NfZkXZ7QJm3TW8uFNPnfBdrZyMgXLJZ9UoNsgXg7QLO7KvNCllDXTnh63Yt8SFc5ht7D6ACXba3WVTlIJHYeh1p2JVj6h0LUY1jxRiPMo4NqfTcfb3XWB8Bxwih5M+wzfywb3BWcaOOk6qA8Xh/Zh/V/BkTu2NWuGRRMqtrUDqDTPC0W72E5H14wElgFPz4Ipru+CtJnG6z2oOskguyg2gWpXTwRBQR1YaMaI+Knto6Wxrgq1HE9ibz9H8mDcT3oziQ0XLDzoAfZ8KzzQHnzZehM75RL6u7uwIDAQAB
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    ports:
      - "8086:8086"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - APP_JWT_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAugRSmCOipKNml+04CQrYH2JcUT24HcgabT37pHDZaBeC49pkrGVm2NfZkXZ7QJm3TW8uFNPnfBdrZyMgXLJZ9UoNsgXg7QLO7KvNCllDXTnh63Yt8SFc5ht7D6ACXba3WVTlIJHYeh1p2JVj6h0LUY1jxRiPMo4NqfTcfb3XWB8Bxwih5M+wzfywb3BWcaOOk6qA8Xh/Zh/V/BkTu2NWuGRRMqtrUDqDTPC0W72E5H14wElgFPz4Ipru+CtJnG6z2oOskguyg2gWpXTwRBQR1YaMaI+Knto6Wxrgq1HE9ibz9H8mDcT3oziQ0XLDzoAfZ8KzzQHnzZehM75RL6u7uwIDAQAB
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  system-events-service:
    build:
      context: ./system-events-service
      dockerfile: Dockerfile
    container_name: system-events-service
    ports:
      - "8087:8087"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - APP_JWT_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAugRSmCOipKNml+04CQrYH2JcUT24HcgabT37pHDZaBeC49pkrGVm2NfZkXZ7QJm3TW8uFNPnfBdrZyMgXLJZ9UoNsgXg7QLO7KvNCllDXTnh63Yt8SFc5ht7D6ACXba3WVTlIJHYeh1p2JVj6h0LUY1jxRiPMo4NqfTcfb3XWB8Bxwih5M+wzfywb3BWcaOOk6qA8Xh/Zh/V/BkTu2NWuGRRMqtrUDqDTPC0W72E5H14wElgFPz4Ipru+CtJnG6z2oOskguyg2gWpXTwRBQR1YaMaI+Knto6Wxrgq1HE9ibz9H8mDcT3oziQ0XLDzoAfZ8KzzQHnzZehM75RL6u7uwIDAQAB
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_healthy

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service
    ports:
      - "8088:8088"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
      - APP_JWT_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAugRSmCOipKNml+04CQrYH2JcUT24HcgabT37pHDZaBeC49pkrGVm2NfZkXZ7QJm3TW8uFNPnfBdrZyMgXLJZ9UoNsgXg7QLO7KvNCllDXTnh63Yt8SFc5ht7D6ACXba3WVTlIJHYeh1p2JVj6h0LUY1jxRiPMo4NqfTcfb3XWB8Bxwih5M+wzfywb3BWcaOOk6qA8Xh/Zh/V/BkTu2NWuGRRMqtrUDqDTPC0W72E5H14wElgFPz4Ipru+CtJnG6z2oOskguyg2gWpXTwRBQR1YaMaI+Knto6Wxrgq1HE9ibz9H8mDcT3oziQ0XLDzoAfZ8KzzQHnzZehM75RL6u7uwIDAQAB
    depends_on:
      mysql-db:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_started

volumes:
  db_data:
  rabbitmq_data: