CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS propertydb;
CREATE DATABASE IF NOT EXISTS reservationdb;
CREATE DATABASE IF NOT EXISTS paymentdb;
CREATE DATABASE IF NOT EXISTS reviewdb;
CREATE DATABASE IF NOT EXISTS notificationdb;
CREATE DATABASE IF NOT EXISTS analyticsdb;
CREATE DATABASE IF NOT EXISTS systemeventsdb;
