spring.application.name=api-gateway

# Centralizovana konfiguracija (Config Server)
spring.config.import=optional:configserver:http://config-server:8888
spring.cloud.config.fail-fast=true

# Default port ako Config Server nije dostupan
server.port=8080

# Aktivni profil
spring.profiles.active=dev
