spring.application.name=payment-service
server.port=8084

# Centralizovana konfiguracija (Config Server) - opcioni import
spring.config.import=optional:configserver:http://config-server:8888

# MySQL Database
spring.datasource.url=jdbc:mysql://mysql-db:3306/paymentdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Eureka klijent (service discovery)
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

# Actuator (healthchecks + circuit breaker)
management.endpoints.web.exposure.include=health,info,metrics,env,circuitbreakers
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# JWT (mora biti identican kao u user-service)
app.jwt.secret=${JWT_SECRET:very-long-secret-key-that-must-be-at-least-32-characters-long}

# Feign timeouts
spring.cloud.openfeign.client.config.default.connect-timeout=2000
spring.cloud.openfeign.client.config.default.read-timeout=3000
spring.cloud.openfeign.circuitbreaker.enabled=true

# Resilience4j circuit breaker (reservation-service)
resilience4j.circuitbreaker.instances.reservation-service.register-health-indicator=true
resilience4j.circuitbreaker.instances.reservation-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.reservation-service.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.reservation-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.reservation-service.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.reservation-service.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.reservation-service.automatic-transition-from-open-to-half-open-enabled=true
