spring.application.name=analytics-service

# Import configuration from Config Server
# Using 'config-server' hostname for Docker networking
spring.config.import=optional:configserver:http://config-server:8888

# Fail fast if config server is unreachable (to trigger retries)
spring.cloud.config.fail-fast=true

# Default port in case config server is unreachable
server.port=8088

# Profile specific settings
spring.profiles.active=dev
