# API Gateway - DEV profile
# Verbose logging in dev
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.com.bookingnwt.apigateway=DEBUG
logging.level.reactor.netty=INFO
# More permissive rate limiting in dev
gateway.rate-limit.replenish-rate=100
gateway.rate-limit.burst-capacity=200
