# Notification Service - DEV profile
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Verbose logging in dev
logging.level.com.bookingnwt.notificationservice=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.feign=DEBUG
# Shorter circuit breaker timeouts for dev
resilience4j.circuitbreaker.instances.system-events-service.wait-duration-in-open-state=5s
