# System Events Service - DEV profile
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Verbose logging in dev
logging.level.com.bookingnwt.systemevents=DEBUG
logging.level.org.springframework.security=DEBUG
